# Generated by Django 3.0.5 on 2020-07-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
